### ISSUE TITLE
BOM generated code is failed due to parse error on variable vpn_ingress_rules default value

### ISSUE THREAD

**Issue by indirakalagara** [cloud-native-toolkit/terraform-aws-vpn-server#21]
variable “vpn_ingress_rules” {
  type = string
  description = “the value of vpn_ingress_rules”
  default = “\”[\n        {\n          from_port   = 22\n          to_port     = 22\n          protocol    = \\“tcp\\“\n          cidr_block  = \\“0.0.0.0/0\\“\n          description = \\“ssh\\“\n        },\n        {\n          from_port   = 80\n          to_port     = 80\n          protocol    = \\“tcp\\“\n          cidr_block  = \\“0.0.0.0/0\\“\n          description = \\“web\\“\n        },\n    ]\“”
}

**Comment by faheemshai** [comment]
updated the default value for ingress rule issue is resolve now
